DROP TYPE IF EXISTS chart_type;
CREATE TYPE "chart_type" AS ENUM (
  'COUNTER',
  'LINE'
);

create table charts
(
    id         integer generated by default as identity,
    name       varchar(256)            not null,
    chart_type chart_type              not null,
    created_at timestamp default now() not null,
    primary key (id),
    unique (name)
);

comment on table charts is 'Table contains chart description and sync info';

alter table charts
    owner to postgres;

